name: Release Plz

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: "Full Commit SHA to release"
      dry_run:
        type: boolean
        description: "DryRun release"
        required: false
        default: false

permissions:
  # trust publish needs
  id-token: write
  # push tag
  contents: write

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    environment: crate
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit }}

      - uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: warm

      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth

      - name: Publish
        run: cargo publish
        if: ${{ !inputs.dry_run }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Dry Run Publish
        run: cargo publish --dry-run
        if: inputs.dry_run
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Push tag
        run: |
          version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name == "rspack_resolver") | .version')
          echo tagging v$version
          git config --global --add safe.directory /github/workspace
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git tag v$version -m v$version
          git push origin v$version
